# Generated by Django 3.2.6 on 2021-08-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Issue', 'Issue'), ('Story', 'Story'), ('Epic', 'Epic'), ('Task', 'Task')], default='Issue', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('InProgress', 'Inprogress'), ('CodeReview', 'Codereview'), ('Completed', 'Completed'), ('Close', 'Close')], default='Open', max_length=10)),
                ('assignee', models.CharField(max_length=50)),
                ('labels', models.CharField(max_length=50)),
                ('watchers', models.CharField(max_length=50)),
                ('estimated_time', models.TimeField()),
                ('logged_time', models.TimeField()),
                ('reporter', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.project')),
            ],
        ),
    ]
